### ISSUE TITLE
Unable to create a new sketch

### ISSUE THREAD

**Issue by kevin-hart** [thelastoutpostworkshop/arduino-maker-workshop#6]
unable to create new sketch -  see screen capture below.

![image](https://github.com/user-attachments/assets/35ec896a-7374-4668-b80c-2398b5b51571)

extension is reporting following errors.

![image](https://github.com/user-attachments/assets/3b7c3b87-ceb4-458d-8664-2da807f1ba5f)

and when trying to add 

Boards Manager is showing that I have the following boards installed.

![image](https://github.com/user-attachments/assets/6673850b-e813-4c97-906b-8acb2d2b8550)

however, when I try to select a board I get the following errors.  

![image](https://github.com/user-attachments/assets/219c2737-097f-4489-bd63-66af86c84c83)

I created a new Profile and installed the Arduino Maker Workshop extension - which then installed its dependencies 

![image](https://github.com/user-attachments/assets/a960a05f-dbd1-4201-b164-056e9afc6f86)

**Comment by thelastoutpostworkshop** [comment]
Are you on Windows ?
If yes, copy what's in the "Arduino Extension" output Window 
![image](https://github.com/user-attachments/assets/f9dbfedc-89d4-4c31-b310-d754dd8ba16a)
 and also what's in the "Arduino CLI" output Window.
![image](https://github.com/user-attachments/assets/846a47c6-d630-4e57-8ce2-f823fe7588a1)

**Comment by kevin-hart** [comment]
> Are you on Windows ? If yes, copy what's in the "Arduino Extension" output Window ![image](https://private-user-images.githubusercontent.com/127604345/398184501-f9dbfedc-89d4-4c31-b310-d754dd8ba16a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzgzOTEsIm5iZiI6MTczNDk3ODA5MSwicGF0aCI6Ii8xMjc2MDQzNDUvMzk4MTg0NTAxLWY5ZGJmZWRjLTg5ZDQtNGMzMS1iMzEwLWQ3NTRkZDhiYTE2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxODIxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODM4OGYzZTVkODRlODIyZGM4ZjY2NTAyNjQ4NGFkZmY1NGNiMTYxMTc5NDAwMWYyYmU4M2I3MjA1NGQ2YzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OF8m5v96Gv8fhSXh1bf_zMsjCDFrhKr3UfcafOPaEJs) and also what's in the "Arduino CLI" output Window. ![image](https://private-user-images.githubusercontent.com/127604345/398184548-846a47c6-d630-4e57-8ce2-f823fe7588a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzgzOTEsIm5iZiI6MTczNDk3ODA5MSwicGF0aCI6Ii8xMjc2MDQzNDUvMzk4MTg0NTQ4LTg0NmE0N2M2LWQ2MzAtNGU1Ny04Y2UyLWY4MjNmZTc1ODhhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxODIxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2Q1Nzc1YjJmZGEyOWZhNjc0YzNkYTk2MzhjOTZiNTU3ZGY3ZjU2ODBiYzViYzY3M2U0M2M0NmJjNTYzNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9KzTncRsFMJb-NKLZdUdny4cUeNzgOfODgySV4xi5SY)



Yes - I'm running windows (Windows 10 22H2 to be specific)   -  See below for VS code version

![image](https://github.com/user-attachments/assets/b7636ff4-8afb-4647-900f-157653a87ae3)



Outputs requested (I think)


Arduino Extension started
Arduino CLI is ready, path: c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
Arduino Config file is good
Arduino Web view ready
Set Board FQBN=:arduino:avr:uno
Set Board FQBN=:arduino:avr:uno
Set Board FQBN=:arduino:avr:uno




Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
version --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
core update-index

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
config dump --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
core update-index

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
lib search --omit-releases-details --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
lib list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
outdated --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board search --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
core search -a --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
config dump --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\kevin\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.6-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

**Comment by thelastoutpostworkshop** [comment]
I think I know what's happening, open Visual Studio Code in a folder where you want your sketch to be stored, for example in the your documents folder and try creating a new sketch.

**Comment by kevin-hart** [comment]
Thanks that works.   Will have a play.Kevin Sent from Outlook for AndroidFrom: thelastoutpostworkshop ***@***.***>Sent: Monday, December 23, 2024 6:43:50 pmTo: thelastoutpostworkshop/arduino-maker-workshop ***@***.***>Cc: Kevin Hart ***@***.***>; Author ***@***.***>Subject: Re: [thelastoutpostworkshop/arduino-maker-workshop] Unable to create a new sketch (Issue #6)
I think I know what's happening, open Visual Studio Code in a folder where you want your sketch to be stored, for example in the your documents folder and try creating a new sketch.

**Comment by peno64** [comment]
I have exactly the same problem. However starting in another folder where I can write in does not help.
I also have the ENOENT: no such gile or directory, open ''

And I can't create a new sketch because the option is just not there. It is also on the exact same windows version.

![image](https://github.com/user-attachments/assets/6f30c574-36a2-4dd1-b859-47c441e49564)
![image](https://github.com/user-attachments/assets/3063864a-2196-48a9-9ce0-c87294c48ef4)

![image](https://github.com/user-attachments/assets/95d7e1d9-1009-4612-860c-3d9e524230b6)

**Comment by peno64** [comment]
![image](https://github.com/user-attachments/assets/0dd69530-e466-46df-8cab-7f7aff580e35)

**Comment by thelastoutpostworkshop** [comment]
If you open vscode in a folder where you have write permission and you get the error, post the content of the output windows "Arduino CLI" and "Arduino Extension" here

**Comment by peno64** [comment]
Arduino CLI:

Running Arduino CLI...
c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe
version --json

Running Arduino CLI...
c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe
core update-index

Running Arduino CLI...
c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe
config dump --json

Running Arduino CLI...
c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe
core update-index

Running Arduino CLI...
c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe
board list --json

Running Arduino CLI...
c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe
outdated --json


Arduino Extension:

Arduino Extension started
Arduino CLI is ready, path: c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe
Arduino Config file is good
Arduino Web view ready
New Port=:COM4

**Comment by peno64** [comment]
I now installed it on a fresh new windows 11 computer and exactly the same problem. Also note when I go to "Board Selection" that no boards are shown at all. If I go to board configuration I have there the button select a board first but again nothing happens

**Comment by peno64** [comment]
Boards are installed...

![image](https://github.com/user-attachments/assets/4a09a786-e836-40d0-b091-3600c1ac7591)

**Comment by thelastoutpostworkshop** [comment]
Open a command shell where the arduino-cli is located : 
`c:\Users\mail.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\arduino-cli.exe`
and run this command : `arduino-cli sketch new MySketch`
paste the output of the command

**Comment by peno64** [comment]
Seems to work fine: 

C:\Windows\System32>cd "C:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32"

C:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32>arduino-cli sketch new mysketch
Sketch created in: C:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\mysketch

C:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32>cd mysketch

C:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\mysketch>dir
 Volume in drive C is Windows
 Volume Serial Number is 243A-4A88

 Directory of C:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\mysketch

28/12/2024  17:04    <DIR>          .
28/12/2024  17:04    <DIR>          ..
28/12/2024  17:04                35 mysketch.ino
               1 File(s)             35 bytes
               2 Dir(s)  645.877.010.432 bytes free

C:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.7-win32-x64\arduino_cli\win32\mysketch>

**Comment by thelastoutpostworkshop** [comment]
if you open that sketch in vscode is the extension working ?

**Comment by peno64** [comment]
I opened it via File, Open and I get:

![image](https://github.com/user-attachments/assets/c59decc1-3a7b-41d0-bef0-cfd756727451)

But the workshop is still an empty screen:

![image](https://github.com/user-attachments/assets/6b9d3c3b-9f87-4ea9-bfdc-036243aa853e)

**Comment by peno64** [comment]
When I hoover over Compile at says that it is disabled, not an Arduino Project:

![image](https://github.com/user-attachments/assets/bb2a9c74-3cd1-4964-bbec-c663b6b94bc0)

**Comment by peno64** [comment]
When I do Help I see that Visual Studio Code is a version from last week. Would it be that the extension doesn't work anymore with the latest VS version?

![image](https://github.com/user-attachments/assets/da9429eb-f04a-44dc-9a58-3ccc98cf696c)

**Comment by thelastoutpostworkshop** [comment]
It's compatible with the latest version of VSCode.  In the folder of that sketch, there should a .vscode folder and inside it an Arduino.json file, if it's there, paste the content here

**Comment by peno64** [comment]
No, there is no subfolder .vscode
even not hidden

**Comment by thelastoutpostworkshop** [comment]
Here is a test version of the extension that log more errors : https://drive.google.com/file/d/1EKUWHStfTiwXvidHHeSr0pkt2maRgmyH/view?usp=drive_link
It's a .vsix file in a zip.
- uncompress the zip
- uninstall the official extension in vscode
- install this test version in vscode with the command "Extension: Install from VSIX... (CTRL+SHIFT+P)
- reproduce the error and paste the content of the "Arduino Extension" output

**Comment by peno64** [comment]
send a request to be able to download the file

**Comment by peno64** [comment]
Arduino Extension started on win32
Problem : cannot get projectFullPath
Arduino CLI is ready, path: c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.93\arduino_cli\win32\arduino-cli.exe
Arduino Config file is good
Arduino Web view ready

**Comment by thelastoutpostworkshop** [comment]
So the errors cannot get projectFullPath occurs when the extension attempt to get the path of your workspace folder in vscode : https://code.visualstudio.com/docs/editor/workspaces
This is strange that your vscode has no workspace folder, it's not supposed to be.

**Comment by peno64** [comment]
Ok, I did the following from your link: "File > Open Folder... menu, and then selecting a folder."

and now I have the create a new sketch input:

![image](https://github.com/user-attachments/assets/83bea709-1141-486f-8aa2-edc34543e476)

So after you freshly installed visual code it seems there is no workspace defined yet...

**Comment by peno64** [comment]
However... The button "SELECT A BOARD FIRST" is still doing nothing and nothing extra in the Arduino Extension output...

**Comment by peno64** [comment]
Can you also add debugging when "SELECT a BOARD FIRST" is chosen to see why nothing happens?

**Comment by peno64** [comment]
When I click on "SELECT A BOARD FIRST", the following screen first appears but after a second it becomes empty:

![image](https://github.com/user-attachments/assets/c886915d-c593-4b3a-b439-5217d16b5ff7)

And there are boards installed:

![image](https://github.com/user-attachments/assets/5f30ecd7-1c2f-4899-845f-36ec14c3f939)

**Comment by thelastoutpostworkshop** [comment]
You should now have an arduino.json file inside the .vscode folder, paste the content

**Comment by peno64** [comment]
{
  "port": "",
  "configuration": "",
  "output": "build",
  "board": "",
  "programmer": "",
  "useProgrammer": false,
  "configurationRequired": false
}

**Comment by thelastoutpostworkshop** [comment]
Try running this commands where the arduino cli is located : 
`arduino-cli board search > boardsearch.json`
This will create the file boardsearch.json, zip it and paste it here.

**Comment by peno64** [comment]
[boardsearch.json](https://github.com/user-attachments/files/18268908/boardsearch.json)

**Comment by thelastoutpostworkshop** [comment]
Sorry, i forgot an option in the command, it is:
`arduino-cli board search --json > boardsearch.json`
Also run this command paste the output here:
`arduino-cli config dump`

**Comment by peno64** [comment]
[boardsearch.zip](https://github.com/user-attachments/files/18269632/boardsearch.zip)

arduino-cli config dump:

board_manager:
    additional_urls: []
directories:
    data: C:\Users\mail\AppData\Local\Arduino15
    downloads: C:\Users\mail\AppData\Local\Arduino15\staging
    user: C:\Users\mail\Documents\Arduino

**Comment by thelastoutpostworkshop** [comment]
I have create another vsix : https://drive.google.com/file/d/1vtWPBzSvDI3lpVfEmglQ2zEDbZ0nGar9/view?usp=drive_link
Reproduce the error and paste the output of "Arduino Extension"

**Comment by peno64** [comment]
Arduino Extension started on win32
Workspace is c:\brol\arduino\test
Arduino CLI is ready, path: c:\Users\mail\.vscode\extensions\thelastoutpostworkshop.arduino-maker-workshop-0.4.94\arduino_cli\win32\arduino-cli.exe
Arduino Config file is good
Arduino Web view ready
Sending Board search...
Board search sent

I am afraid that this won't give much information. The last two lines appear when I chose to select the board.

**Comment by thelastoutpostworkshop** [comment]
I found what the problem is. I am solving it and will send you another .vsix

**Comment by thelastoutpostworkshop** [comment]
here is the new vsix to test : https://drive.google.com/file/d/1pHM0tUC1KuKBAFVu_crGk79QscpigA_o/view?usp=drive_link

**Comment by peno64** [comment]
Yes! That solves the issue.
Thank you very much. I hope this fix will also help others.
And maybe also add a test in your code if no workspace is selected that an apropriate message is given.

**Comment by thelastoutpostworkshop** [comment]
Thanks for having the patience to help make the extension better.
Yes I have added a message when no workspace is selected.
I will push the official version with the fix soon.

**Comment by thelastoutpostworkshop** [comment]
Extension v0.5.0 pushed on the vscode marketplace that solved this problem.
