### ISSUE TITLE
CLI: Failed to get library available

### ISSUE THREAD

**Issue by mspcbs** [thelastoutpostworkshop/arduino-maker-workshop#7]
Library Manager , CLI: Failed to get library available

**Comment by thelastoutpostworkshop** [comment]
What is the OS of your computer ?
Copy the output of the "Arduino CLI" output window 
![image](https://github.com/user-attachments/assets/0c5cd661-caab-4c65-a230-554f2be2ff24)
and the "Arduino Extension" Window 
![image](https://github.com/user-attachments/assets/10703b71-a84e-4a08-8d06-bd3b4054089e)

**Comment by Maxbeth2** [comment]
I get the same problem, here is the output from the Arduino CLI:

```
Running Arduino CLI...
/Users/max/.vscode/extensions/thelastoutpostworkshop.arduino-maker-workshop-0.4.92-darwin-arm64/arduino_cli/darwin/arm64/arduino-cli
version --json
Failed to run command: spawn /Users/max/.vscode/extensions/thelastoutpostworkshop.arduino-maker-workshop-0.4.92-darwin-arm64/arduino_cli/darwin/arm64/arduino-cli EACCES
Command failed with code -13.
```

And the extension:

```
Arduino Extension started on darwin
Cannot get CLI version
```

**Comment by thelastoutpostworkshop** [comment]
I have created a new issue since your on a Mac : https://github.com/thelastoutpostworkshop/arduino-maker-workshop/issues/12
